const sideMenuConfig = {
  apiDocs: {
    "forcedNavOrder": [
      "/api-docs/basic-concepts",
      "/api-docs/querying",
      "/api-docs/content-management",
      "/api-docs/collaboration",
      "/api-docs/users-and-groups",
      "/api-docs/permissions",
      "/api-docs/sharing",
      "/api-docs/preview"
    ],
    "collapsedNav": [
      "/api-docs/querying",
      "/api-docs/content-management",
      "/api-docs/collaboration",
      "/api-docs/users-and-groups",
      "/api-docs/permissions",
      "/api-docs/sharing",
      "/api-docs/preview"
    ],
  },
  concepts: {
    "forcedNavOrder": [
      "/concepts/introduction",
      "/concepts/what-is-headless-cms",
      "/concepts/what-is-content-as-a-service",
      "/concepts/what-is-snaas",
      "/concepts/overview-of-snaas",
      "/concepts/content",
      "/concepts/content-models",
      "/concepts/content-tree",
      "/concepts/content-relations",
      "/concepts/content-management",
      "/concepts/content-types",
      "/concepts/content-templates",
      "/concepts/content-scheduling",
      "/concepts/search",
      "/concepts/workspace",
      "/concepts/trash",
      "/concepts/versioning",
      "/concepts/simple-approval",
      "/concepts/user-management",
      "/concepts/role-based-permissions",
      "/concepts/document-level-permissions",
      "/concepts/custom-roles-and-permissions",
      "/concepts/sharing",
      "/concepts/actions",
      "/concepts/authentication",
      "/concepts/rest-api",
      "/concepts/office-online-editing",
      "/concepts/client-side-forms",
      "/concepts/settings",
      "/concepts/webhooks",
      "/concepts/localization",
      "/concepts/logging",
      "/concepts/document-previews",
    ],
  },
  tutorials: {},
  guides: {},
  integrations: {}
}

module.exports = sideMenuConfig;
